web/lib/web_web/router.ex
defmodule WebWeb.Router do
  use WebWeb, :router
  use Plug.ErrorHandler

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    # plug(PublicKeys.JwtPlug, sub: Application.get_env(:public_keys, :sub))
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", WebWeb do
    pipe_through :browser # Use the default browser stack

    resources "/users",            UserController, only: [:index, :show, :new, :create, :edit, :update]
    resources "/events",           EventController, only: [:index, :show, :new, :create, :edit, :update]
    delete    "/events/:id",       EventController, :delete
    get       "/auth",             EventController, :index
    resources "/registrations",    RegistrationController, only: [:index, :show, :create, :update, :delete]
    get       "/",                 PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", WebWeb do
  #   pipe_through :api
  # end

  def handle_errors(conn, %{kind: kind, reason: reason, stack: stack} = err) do
    #IO.inspect "Something happened when handling web request for the user:"
    # IO.inspect conn.assigns.current_user
    #IO.inspect "The error was:"
    #IO.inspect err

    conn
  end
end

web/lib/web_web/views/layout_view.ex
defmodule WebWeb.LayoutView do
  use WebWeb, :view

  def navbar(assigns) do
    render("navbar.html", assigns)
  end
end

web/lib/web_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>CG · Meetup</title>
    <link rel="stylesheet" href="<%= Routes.static_url(@conn, "/css/app.css") %>"/>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <script src="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.11.0/js/okta-sign-in.min.js" type="text/javascript"></script>
    <link href="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.11.0/css/okta-sign-in.min.css" type="text/css" rel="stylesheet"/>
    <link href="https://ok1static.oktacdn.com/assets/js/sdk/okta-signin-widget/2.11.0/css/okta-theme.css" type="text/css" rel="stylesheet"/>
  </head>
  <body>
    <%= navbar assigns  %>

    <div class="container">
      <div class="section">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= render @view_module, @view_template, assigns %>
      </div>
    </div>

    <footer class="page-footer blue-grey darken-3">
      <div class="container">
        <div class="row">
          <div class="col l6 s12">
            <h5 class="white-text">MEETUP</h5>
            <p class="grey-text text-lighten-4">A labor of love to help people connect with each other.</p>
          </div>
        </div>
      </div>
      <div class="footer-copyright center">
        <div class="container">
        Made for Capital Group Companies
        </div>
      </div>
    </footer>

    <script type="text/javascript" src="<%= Routes.static_url(@conn, "/js/app.js") %>"></script>
    <!-- script type="text/javascript" src="<%= Routes.static_url(@conn, "/js/materialize/materialize.min.js") %>"></script -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  </body>
</html>

web/lib/web_web/templates/layout/navbar.html.eex
<nav class="navbar-fixed blue darken-2" role="navigation">
    <div class="nav-wrapper container">
        <a href="#!" class="brand-logo"><i class="material-icons">cloud</i>Meetup</a>
        <a href="#" data-target="mobile-meetup" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <%= render "navbar_item.html", text: "Search", conn: @conn, path: Routes.event_path(@conn, :index) %>
            <%= render "navbar_item.html", text: "Directory", conn: @conn, path: Routes.user_path(@conn, :index) %>
            <%= render "navbar_item.html", text: "Create Event", conn: @conn, path: Routes.event_path(@conn, :new) %>
        </ul>
    </div>
</nav>

<ul class="sidenav" id="mobile-meetup">
    <li><%= link "Search", to: Routes.event_path(@conn, :index) %></li>
    <li><%= link "Directory", to: Routes.user_path(@conn, :index) %></li>
    <li><%= link "Create Event", to: Routes.event_path(@conn, :new) %></li>
</ul>

web/lib/web_web/templates/layout/navbar_item.html.eex
<%= if Path.join(["/" | @conn.path_info]) == @path do %>
    <li class="active">
<% else %>
    <li>
<% end %>
        <%= link @text, to: @path %>
    </li>